Repository mongo-express/mongo-express, pull requests merged in 2022-09, with the labels that each got.

#580 Fix loadDocument() when current URL has a query string
  lib/scripts/collection.js
Labels: needs_testing

#945 Set package-ecosystem to yarn in Dependabot
  .github/dependabot.yml
Labels: needs_testing

#950 Update json2csv to v5
  .github/dependabot.yml
  lib/csv.js
  package.json
  yarn.lock
Labels: dependencies

#955 Add update package.json in Dependabot
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: bug, dependencies

#958 Fix runAggregate state
  lib/routes/collection.js
Labels: bug

#951 Simplify/improve queries logic
  lib/routes/collection.js
Labels: enhancement, feature

#974 Replace reindex catch
  lib/routes/collection.js
Labels: enhancement

#602 Fixed Issue #596 mongo-express now running with Inline Parameters
  app.js
  config.default.js
Labels: needs_testing

#583 Update/simplify Dockerfile
  Dockerfile
Labels: needs_testing

#989 Update dependency version of codemirror
  package.json
  yarn.lock
Labels: dependencies

#981 added sanitizing for file input
  lib/routes/collection.js
  lib/scripts/collection.js
  lib/scripts/escapeHtml.js
  package.json
  yarn.lock
Labels: security, feature

#987 Add missing dotenv
  config.default.js
  package.json
  yarn.lock
Labels: bug, feature

#943 Add URL as hyperlink in collection
  lib/filters.js
  lib/views/collection.html
Labels: feature, needs_testing

#996 Fix import function
  lib/routes/collection.js
Labels: bug

#993 Fix export functions
  lib/routes/collection.js
  lib/views/collection.html
  package.json
  test/lib/routers/collectionSpec.js
  yarn.lock
Labels: bug, waiting-peer-review

#994 Improve code unicorn
  .eslintrc.yml
  app.js
  config.default.js
  lib/bson.js
  lib/db.js
  lib/filters.js
  lib/middleware.js
  lib/router.js
  lib/routes/collection.js
  lib/routes/database.js
  lib/routes/document.js
  lib/routes/gridfs.js
  lib/routes/index.js
  lib/scripts/collection.js
  lib/scripts/document.js
  lib/utils.js
  lib/views/layout.html
  package.json
  test/lib/utilsSpec.js
  yarn.lock
Labels: enhancement, draft, feature
