Repository mongo-express/mongo-express, pull requests merged in 2022-12, with the labels that each got.

#1051 Use replace document on update
  lib/routes/document.js
Labels: bug

#1053 Replace custom pager and pagination with paginator-bottom
  lib/routes/collection.js
  lib/scripts/collection.js
  lib/views/collection.html
  lib/views/layout.html
  package.json
  yarn.lock
Labels: bug, feature

#1054 Remove dirty class of read_only
  lib/views/collection.html
Labels: bug

#1080 Add Mongo Express Docker Extension under README
  README.md
Labels: enhancement

#1088 Improve find and aggregate
  lib/routes/collection.js
Labels: enhancement
