Repository mongo-express/mongo-express, pull requests merged in 2022-10, with the labels that each got.

#1009 Replace old _buildMongoQuery with _getQuery
  lib/routes/collection.js
Labels: bug

#552 Support for collection view showing UUIDs and searches allowing UUIDs (BinData type 4)
  README.md
  lib/filters.js
  lib/router.js
  lib/routes/collection.js
  lib/utils.js
  lib/views/collection.html
  package.json
  patches/ejson-shell-parser+1.1.3.patch
  patches/mongodb-query-parser+2.4.6.patch
  test/lib/filtersSpec.js
  test/lib/routers/documentSpec.js
  test/lib/utilsSpec.js
  yarn.lock
Labels: feature, needs_testing, needs_changes

#1015 Update express to 4.18.2
  package.json
  yarn.lock
Labels: dependencies

#988 Update yarn to berry version
  .github/workflows/standard-ci.yml
  .gitignore
  .yarn/patches/ejson-shell-parser-npm-1.1.3-6aacdd642d.patch
  .yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch
  .yarn/patches/renderjson-npm-1.4.0-b198ae5f7e.patch
  .yarn/releases/yarn-4.0.0-rc.26.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: dependencies, draft, feature
