Repository mongo-express/mongo-express, pull requests merged in 2023-07, with the labels that each got.

#1146 chore: replace renderjson devDep from patch to github repo
  .yarn/patches/renderjson-npm-1.4.0-b198ae5f7e.patch
  package.json
  yarn.lock
Labels: dependencies

#1094 chore!: remove Node 14
  .eslintrc.yml
  .github/workflows/standard-ci.yml
  lib/filters.js
  lib/router.js
  lib/routes/collection.js
  lib/scripts/collection.js
  package.json
Labels: enhancement, draft, upgrade, deprecate

#957 chore!: remove individual parameters
  README.md
  app.js
  config.default.js
Labels: enhancement, deprecate, waiting-peer-review, needs_changes

#1239 fix: improve commander update
  app.js
Labels: dependencies, deprecate

#1240 docs: update commander README
  README.md
  app.js
Labels: enhancement, feature

#1254 fix: workaround for broken BinData serialization in mongodb-query-parser
  .yarn/patches/mongodb-query-parser-npm-3.1.2-a9264cfd1f.patch
  package.json
  test/lib/bsonSpec.js
  yarn.lock
Labels: bug, enhancement

#1224 chore!: update mongodb and bson to v5
  lib/bson.js
  lib/filters.js
  lib/router.js
  lib/routes/collection.js
  package.json
  test/lib/bsonSpec.js
  test/lib/filtersSpec.js
  test/lib/routers/documentSpec.js
  test/lib/utilsSpec.js
  yarn.lock
Labels: dependencies, draft, upgrade, deprecate

#1260 chore: replace json2csv with @json2csv/plainjs
  lib/csv.js
  package.json
  yarn.lock
Labels: dependencies, deprecate

#1261 feat: add allowDiskUse to mongodb options
  README.md
  config.default.js
  lib/routes/collection.js
Labels: feature
