Repository mongo-express/mongo-express, pull requests merged in 2024-07, with the labels that each got.

#1592 fix: add projection to exports
  lib/routes/collection.js
Labels: bug

#1533 feat: use generic package manager
  .github/workflows/standard-ci.yml
  README.md
  package.json
  yarn.lock
Labels: feature

#1599 build: improve CodeQL
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#1600 chore: update yarn to v4.3.1
  .yarn/releases/yarn-4.1.1.cjs
  .yarn/releases/yarn-4.3.1.cjs
  .yarnrc.yml
  package.json
Labels: upgrade

#1604 chore: fix test script and pre-commit
  .husky/pre-commit
  package.json
Labels: enhancement
